### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by yihong0618** [yasoob/nrc-exporter#3]
No heart_rate in gpx.
**Time zone issues are not considered**

Can I  raise a pr?

**Comment by yasoob** [comment]
Yeah for sure! Do open up a PR. I didn’t use to record heart rate data in nrc so didn’t add that functionality in.

**Comment by yasoob** [comment]
Is it okay for you to share a sample NRC activity file with heart-rate data? I don't have one myself.

**Comment by yihong0618** [comment]
You can download from my nrc json like this it contains heart rate data. https://raw.githubusercontent.com/yihong0618/blog/master/data/activities/1593858760016.json
I can take a pr maybe today or tomorrow in my time zone, Thank you.

**Comment by yihong0618** [comment]
@yasoob 
You can download from my `nrc` json like below it contains heart rate data. https://raw.githubusercontent.com/yihong0618/blog/master/data/activities/1593858760016.json
I can take a pr maybe today or tomorrow in my time zone, Thank you.

**Comment by yasoob** [comment]
Thanks!

**Comment by yihong0618** [comment]
time zone fix https://github.com/yasoob/nrc-exporter/pull/4

**Comment by yasoob** [comment]
I already merged that in :)

**Comment by yihong0618** [comment]
@yasoob add heart rate https://github.com/yasoob/nrc-exporter/pull/5
But I don't know which lint do you prefer, black or pep8 or pylint, I didn't do the lint.
