### ISSUE TITLE
Issue regarding activities list 

### ISSUE THREAD

**Issue by snmac13** [yasoob/nrc-exporter#8]
I just want to say thanks for creating this.  Having the NRC data will be so helpful.  I used the 'arc-exporter -t "token"' command and ran into this issue.  Any idea what is going wrong here?  All help will be much appreciated. Thanks!

[+] Starting NRC Exporter
[+] 🏃‍♀️  Getting activities list
[+] 📃  opening page 1 of activities
[+] 📃  opening page 2 of activities
[+] 📃  opening page 3 of activities
[+] 📃  opening page 4 of activities
[+] 📃  opening page 5 of activities
[+] 📃  opening page 6 of activities
[+] 📃  opening page 7 of activities
[+] 📃  opening page 8 of activities
[+] 📃  opening page 9 of activities
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.8.3/bin/nrc-exporter", line 8, in <module>
    sys.exit(main())
  File "/Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/nrc_exporter.py", line 611, in main
    activity_ids = get_activities_list(options)
  File "/Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/nrc_exporter.py", line 306, in get_activities_list
    debug(f"Entry type: {activity['tags'].get('com.nike.running.runtype', '')}")
KeyError: 'tags'

**Comment by yasoob** [comment]
The JSON result coming from Nike is causing this problem. I will need to take a look at the output you are receiving from Nike to fix this. Let me know if you know Python and can run a customized Python script with more debugging output if I share it with you. If you can't do that, we can find a different way to debug this.

**Comment by snmac13** [comment]
yasoob,

Thanks for the response.  I can run the script if you would like.Thanks

**Comment by yihong0618** [comment]
@yasoob it seems that some some synchronized data has no label of tag ?
can we use activity.get("tag", {}).get('com.nike.running.runtype', '') instead

**Comment by yasoob** [comment]
@yihong0618 that is what I thought so as well but didn't have a way to reproduce it. I was gonna suggest @snmac13 to send me the activity file but if you believe that this is definitely the issue, your suggestion seems like a plausible fix. Would you be willing to open a PR?

**Comment by yihong0618** [comment]
> @yihong0618 that is what I thought so as well but didn't have a way to reproduce it. I was gonna suggest @snmac13 to send me the activity file but if you believe that this is definitely the issue, your suggestion seems like a plausible fix. Would you be willing to open a PR?

Yes,  I think I can open a PR later today.

**Comment by yasoob** [comment]
@snmac13 I will make a new pip release soon but in the meantime you can just install nrc-exporter from this repo and hopefully the issue should be resolved :)

**Comment by snmac13** [comment]
Will get to this momentarily.  Sorry for the delay.
